In [2]:
import pandas as pd

In [3]:
people={
    'first':['Ram','Hari','Gopal'],
    'last':['sharma','Yadav','verma'],
    'email':['ram@gmail.com','hari@gmail.com','gopal@live.com']
}

In [4]:
people.get('email')

['ram@gmail.com', 'hari@gmail.com', 'gopal@live.com']

In [5]:
people.get('email')[1]

'hari@gmail.com'

In [6]:
people_df=pd.DataFrame(people)

In [7]:
people_df

   first    last           email
0    Ram  sharma   ram@gmail.com
1   Hari   Yadav  hari@gmail.com
2  Gopal   verma  gopal@live.com

In [8]:
type(people_df)

pandas.core.frame.DataFrame

In [9]:
people_df[['first','email']]

   first           email
0    Ram   ram@gmail.com
1   Hari  hari@gmail.com
2  Gopal  gopal@live.com

In [10]:
people_df.columns

Index(['first', 'last', 'email'], dtype='object')

In [11]:
people_df.iloc[[0,1]]

  first    last           email
0   Ram  sharma   ram@gmail.com
1  Hari   Yadav  hari@gmail.com

In [12]:
people_df.iloc[[0,1],2]

0     ram@gmail.com
1    hari@gmail.com
Name: email, dtype: object

In [13]:
people_df.loc[[0,1],['email','last']]

            email    last
0   ram@gmail.com  sharma
1  hari@gmail.com   Yadav

In [16]:


df = pd.read_csv('./survey_results_public.csv')

In [17]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [18]:
df.shape

(88883, 85)

In [19]:
df.info

<bound method DataFrame.info of        Respondent                                         MainBranch Hobbyist  \
0               1             I am a student who is learning to code      Yes
1               2             I am a student who is learning to code       No
2               3  I am not primarily a developer, but I write co...      Yes
3               4                     I am a developer by profession       No
4               5                     I am a developer by profession      Yes
...           ...                                                ...      ...
88878       88377                                                NaN      Yes
88879       88601                                                NaN       No
88880       88802                                                NaN       No
88881       88816                                                NaN       No
88882       88863                                                NaN      Yes

                                             OpenSourcer  \
0                                                  Never
1                                Less than once per year
2                                                  Never
3                                                  Never
4                             Once a month or more often
...                                                  ...
88878  Less than once a month but more than once per ...
88879                                              Never
88880                                              Never
88881                                              Never
88882                            Less than once per year

                                              OpenSource  \
0      The quality of OSS and closed source software ...
1      The quality of OSS and closed source software ...
2      The quality of OSS and closed source software ...
3      The quality of OSS and closed source software ...
4      OSS is, on average, of HIGHER quality than pro...
...                                                  ...
88878  The quality of OSS and closed source software ...
88879  The quality of OSS and closed source software ...
88880                                                NaN
88881  OSS is, on average, of HIGHER quality than pro...
88882  OSS is, on average, of HIGHER quality than pro...

                                              Employment  \
0                 Not employed, and not looking for work
1                     Not employed, but looking for work
2                                     Employed full-time
3                                     Employed full-time
4                                     Employed full-time
...                                                  ...
88878             Not employed, and not looking for work
88879                                                NaN
88880                                 Employed full-time
88881  Independent contractor, freelancer, or self-em...
88882             Not employed, and not looking for work

                      Country         Student  \
0              United Kingdom              No
1      Bosnia and Herzegovina  Yes, full-time
2                    Thailand              No
3               United States              No
4                     Ukraine              No
...                       ...             ...
88878                  Canada              No
88879                     NaN             NaN
88880                     NaN             NaN
88881                     NaN             NaN
88882                   Spain  Yes, full-time

                                                 EdLevel  \
0                              Primary/elementary school
1      Secondary school (e.g. American high school, G...
2               Bachelor’s degree (BA, BS, B.Eng., etc.)
3               Bachelor’s degree (BA, BS, B.Eng., etc.)
4               Bachelor’s degree (BA, BS, B.Eng., etc.)
...                                                  ...
88878                          Primary/elementary school
88879                                                NaN
88880                                                NaN
88881                                                NaN
88882                 Professional degree (JD, MD, etc.)

                                          UndergradMajor  ...  \
0                                                    NaN  ...
1                                                    NaN  ...
2                          Web development or web design  ...
3      Computer science, computer engineering, or sof...  ...
4      Computer science, computer engineering, or sof...  ...
...                                                  ...  ...
88878                                                NaN  ...
88879                                                NaN  ...
88880                                                NaN  ...
88881                                                NaN  ...
88882  Computer science, computer engineering, or sof...  ...

                                  WelcomeChange  \
0       Just as welcome now as I felt last year
1       Just as welcome now as I felt last year
2       Just as welcome now as I felt last year
3       Just as welcome now as I felt last year
4       Just as welcome now as I felt last year
...                                         ...
88878                                       NaN
88879                                       NaN
88880                                       NaN
88881                                       NaN
88882  Somewhat less welcome now than last year

                                            SONewContent   Age Gender Trans  \
0      Tech articles written by other developers;Indu...  14.0    Man    No
1      Tech articles written by other developers;Indu...  19.0    Man    No
2      Tech meetups or events in your area;Courses on...  28.0    Man    No
3      Tech articles written by other developers;Indu...  22.0    Man    No
4      Tech meetups or events in your area;Courses on...  30.0    Man    No
...                                                  ...   ...    ...   ...
88878  Tech articles written by other developers;Tech...   NaN    Man    No
88879                                                NaN   NaN    NaN   NaN
88880                                                NaN   NaN    NaN   NaN
88881                                                NaN   NaN    NaN   NaN
88882  Tech articles written by other developers;Indu...  18.0    Man    No

                     Sexuality  \
0      Straight / Heterosexual
1      Straight / Heterosexual
2      Straight / Heterosexual
3      Straight / Heterosexual
4      Straight / Heterosexual
...                        ...
88878                      NaN
88879                      NaN
88880                      NaN
88881                      NaN
88882  Straight / Heterosexual

                                               Ethnicity Dependents  \
0                                                    NaN         No
1                                                    NaN         No
2                                                    NaN        Yes
3                           White or of European descent         No
4               White or of European descent;Multiracial         No
...                                                  ...        ...
88878                                                NaN         No
88879                                                NaN        NaN
88880                                                NaN        NaN
88881                                                NaN        NaN
88882  Hispanic or Latino/Latina;White or of European...         No

                SurveyLength                  SurveyEase
0      Appropriate in length  Neither easy nor difficult
1      Appropriate in length  Neither easy nor difficult
2      Appropriate in length  Neither easy nor difficult
3      Appropriate in length                        Easy
4      Appropriate in length                        Easy
...                      ...                         ...
88878  Appropriate in length                        Easy
88879                    NaN                         NaN
88880                    NaN                         NaN
88881                    NaN                         NaN
88882  Appropriate in length                        Easy

[88883 rows x 85 columns]>

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              88883 non-null  int64
 1   MainBranch              88331 non-null  object
 2   Hobbyist                88883 non-null  object
 3   OpenSourcer             88883 non-null  object
 4   OpenSource              86842 non-null  object
 5   Employment              87181 non-null  object
 6   Country                 88751 non-null  object
 7   Student                 87014 non-null  object
 8   EdLevel                 86390 non-null  object
 9   UndergradMajor          75614 non-null  object
 10  EduOther                84260 non-null  object
 11  OrgSize                 71791 non-null  object
 12  DevType                 81335 non-null  object
 13  YearsCode               87938 non-null  object
 14  Age1stCode              87634 non-null  object
 15  YearsCodePro            74331 non-null  object
 16  CareerSat               72847 non-null  object
 17  JobSat                  70988 non-null  object
 18  MgrIdiot                61159 non-null  object
 19  MgrMoney                61157 non-null  object
 20  MgrWant                 61232 non-null  object
 21  JobSeek                 80555 non-null  object
 22  LastHireDate            79854 non-null  object
 23  LastInt                 67155 non-null  object
 24  FizzBuzz                71344 non-null  object
 25  JobFactors              79371 non-null  object
 26  ResumeUpdate            77877 non-null  object
 27  CurrencySymbol          71392 non-null  object
 28  CurrencyDesc            71392 non-null  object
 29  CompTotal               55945 non-null  float64
 30  CompFreq                63268 non-null  object
 31  ConvertedComp           55823 non-null  float64
 32  WorkWeekHrs             64503 non-null  float64
 33  WorkPlan                68914 non-null  object
 34  WorkChallenge           68141 non-null  object
 35  WorkRemote              70284 non-null  object
 36  WorkLoc                 70055 non-null  object
 37  ImpSyn                  71779 non-null  object
 38  CodeRev                 70390 non-null  object
 39  CodeRevHrs              49790 non-null  float64
 40  UnitTests               62668 non-null  object
 41  PurchaseHow             61108 non-null  object
 42  PurchaseWhat            62029 non-null  object
 43  LanguageWorkedWith      87569 non-null  object
 44  LanguageDesireNextYear  84088 non-null  object
 45  DatabaseWorkedWith      76026 non-null  object
 46  DatabaseDesireNextYear  69147 non-null  object
 47  PlatformWorkedWith      80714 non-null  object
 48  PlatformDesireNextYear  77443 non-null  object
 49  WebFrameWorkedWith      65022 non-null  object
 50  WebFrameDesireNextYear  62944 non-null  object
 51  MiscTechWorkedWith      59586 non-null  object
 52  MiscTechDesireNextYear  64511 non-null  object
 53  DevEnviron              87317 non-null  object
 54  OpSys                   87851 non-null  object
 55  Containers              85366 non-null  object
 56  BlockchainOrg           48175 non-null  object
 57  BlockchainIs            60165 non-null  object
 58  BetterLife              86269 non-null  object
 59  ITperson                87141 non-null  object
 60  OffOn                   86663 non-null  object
 61  SocialMedia             84437 non-null  object
 62  Extraversion            87305 non-null  object
 63  ScreenName              80486 non-null  object
 64  SOVisit1st              83877 non-null  object
 65  SOVisitFreq             88263 non-null  object
 66  SOVisitTo               88086 non-null  object
 67  SOFindAnswer            87816 non-null  object
 68  SOTimeSaved             86344 non-null  object
 69  SOHowMuchTime           68378 non-null  object
 70  SOAccount               87828 non-null  object
 71  SOPartFreq              74692 non-null  object
 72  SOJobs                  88066 non-null  object
 73  EntTeams                87841 non-null  object
 74  SOComm                  88131 non-null  object
 75  WelcomeChange           85855 non-null  object
 76  SONewContent            69560 non-null  object
 77  Age                     79210 non-null  float64
 78  Gender                  85406 non-null  object
 79  Trans                   83607 non-null  object
 80  Sexuality               76147 non-null  object
 81  Ethnicity               76668 non-null  object
 82  Dependents              83059 non-null  object
 83  SurveyLength            86984 non-null  object
 84  SurveyEase              87081 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 57.6+ MB

In [21]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [22]:


df['Hobbyist'].value_counts()

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [24]:
schema_df = pd.read_csv('./survey_results_schema.csv')

In [25]:
schema_df

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [26]:
schema_df.head()

        Column                                       QuestionText
0   Respondent  Randomized respondent ID number (not in order ...
1   MainBranch  Which of the following options best describes ...
2     Hobbyist                            Do you code as a hobby?
3  OpenSourcer        How often do you contribute to open source?
4   OpenSource  How do you feel about the quality of open sour...

In [27]:
schema_df.head(10)

           Column                                       QuestionText
0      Respondent  Randomized respondent ID number (not in order ...
1      MainBranch  Which of the following options best describes ...
2        Hobbyist                            Do you code as a hobby?
3     OpenSourcer        How often do you contribute to open source?
4      OpenSource  How do you feel about the quality of open sour...
5      Employment  Which of the following best describes your cur...
6         Country          In which country do you currently reside?
7         Student  Are you currently enrolled in a formal, degree...
8         EdLevel  Which of the following best describes the high...
9  UndergradMajor  What was your main or most important field of ...

In [28]:
schema_df.tail(10)

           Column                                       QuestionText
75  WelcomeChange  Compared to last year, how welcome do you feel...
76   SONewContent  Would you like to see any of the following on ...
77            Age  What is your age (in years)? If you prefer not...
78         Gender  Which of the following do you currently identi...
79          Trans                    Do you identify as transgender?
80      Sexuality  Which of the following do you currently identi...
81      Ethnicity  Which of the following do you identify as? Ple...
82     Dependents  Do you have any dependents (e.g., children, el...
83   SurveyLength  How do you feel about the length of the survey...
84     SurveyEase  How easy or difficult was this survey to compl...